// =============================================================================
// Edu-Voice-AI — API Capability Matrix & Contract Verification
// =============================================================================

export interface CapabilityEntry {
  feature: string;
  productionEndpoint: string | null;
  productionSupported: boolean;
  demoSupported: boolean;
  roleRequired: string;
  status: 'confirmed' | 'pending_backend' | 'planned';
  notes: string;
}

export const API_CAPABILITY_MATRIX: CapabilityEntry[] = [
  {
    feature: 'User Profile & Identity',
    productionEndpoint: 'GET /api/v1/me',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Authenticated',
    status: 'confirmed',
    notes: 'Returns current profile, avatar, email, and organization memberships with roles.',
  },
  {
    feature: 'List Organizations',
    productionEndpoint: 'GET /api/v1/organizations',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Authenticated',
    status: 'confirmed',
    notes: 'Returns all organizations the user is a member of.',
  },
  {
    feature: 'Create Organization',
    productionEndpoint: 'POST /api/v1/organizations',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Authenticated',
    status: 'confirmed',
    notes: 'Creates new tenant institution and assigns creator as admin.',
  },
  {
    feature: 'Get/Update Organization',
    productionEndpoint: 'GET, PATCH /api/v1/organizations/{org_id}',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member (GET), Admin (PATCH)',
    status: 'confirmed',
    notes: 'Institution profile, contact information, address, timezone.',
  },
  {
    feature: 'Organization Members',
    productionEndpoint: 'GET /api/v1/organizations/{org_id}/members',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member+',
    status: 'confirmed',
    notes: 'Team member listings with user UUID, email, full name, and role.',
  },
  {
    feature: 'AI Agents List & Create',
    productionEndpoint: 'GET, POST /api/v1/organizations/{org_id}/agents',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member (GET), Admin (POST)',
    status: 'confirmed',
    notes: 'Admission AI counselors (e.g. Maya).',
  },
  {
    feature: 'Agent Configuration',
    productionEndpoint: 'GET, PATCH /api/v1/organizations/{org_id}/agents/{agent_id}/config',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member (GET), Admin (PATCH)',
    status: 'confirmed',
    notes: 'System prompt, voice ID, voice speed, temperature, human handoff phone number & condition.',
  },
  {
    feature: 'Phone Numbers / Telephony',
    productionEndpoint: 'GET, POST /api/v1/organizations/{org_id}/phone-numbers',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member (GET), Admin (POST)',
    status: 'confirmed',
    notes: 'Exotel virtual DIDs (e.g., 040-459-01132).',
  },
  {
    feature: 'Assign Phone Number to Agent',
    productionEndpoint: 'POST /api/v1/organizations/{org_id}/phone-numbers/{phone_id}/assign',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Admin',
    status: 'confirmed',
    notes: 'Maps phone DID directly to an AI admission counselor.',
  },
  {
    feature: 'Calls History & Filtering',
    productionEndpoint: 'GET /api/v1/organizations/{org_id}/calls',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member+',
    status: 'confirmed',
    notes: 'Paginated call sessions with filters: status, direction, agent_id, date range.',
  },
  {
    feature: 'Call Details & Summaries',
    productionEndpoint: 'GET /api/v1/organizations/{org_id}/calls/{call_id}',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member+',
    status: 'confirmed',
    notes: 'Full call summary, sentiment score, detected intent, key topics, action items.',
  },
  {
    feature: 'Call Transcripts',
    productionEndpoint: 'GET /api/v1/organizations/{org_id}/calls/{call_id}/transcript',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member+',
    status: 'confirmed',
    notes: 'Turn-by-turn chat dialogue with timestamps and speaker tags (agent/caller).',
  },
  {
    feature: 'Call Audio Recordings',
    productionEndpoint: 'GET /api/v1/organizations/{org_id}/calls/{call_id}/recording',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member+',
    status: 'confirmed',
    notes: 'Authorized audio streaming URL or presigned storage link.',
  },
  {
    feature: 'Leads CRM Pipeline',
    productionEndpoint: 'GET, POST, PATCH, DELETE /api/v1/organizations/{org_id}/leads',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member (GET), Staff (POST/PATCH), Admin (DELETE)',
    status: 'confirmed',
    notes: 'Lead prospects with qualification, score, stage, notes, counselor assignment.',
  },
  {
    feature: 'Knowledge Base Documents',
    productionEndpoint: 'GET, POST, DELETE /api/v1/organizations/{org_id}/knowledge',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member (GET), Staff (POST), Admin (DELETE)',
    status: 'confirmed',
    notes: 'Uploads PDF/DOCX/TXT metadata, status tracking, vector cleanup.',
  },
  {
    feature: 'RAG Semantic Search Test',
    productionEndpoint: 'POST /api/v1/organizations/{org_id}/knowledge/search',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member+',
    status: 'confirmed',
    notes: 'Tests top-k vector chunk retrieval for student inquiries.',
  },
  {
    feature: 'Counselor Follow-up Tasks',
    productionEndpoint: null,
    productionSupported: false,
    demoSupported: true,
    roleRequired: 'Staff+',
    status: 'pending_backend',
    notes: 'Endpoint /followups not in current API contract. Simulated in Demo Mode only.',
  },
  {
    feature: 'Knowledge Chunk Inspection',
    productionEndpoint: null,
    productionSupported: false,
    demoSupported: true,
    roleRequired: 'Member+',
    status: 'pending_backend',
    notes: 'Endpoint /chunks not in current API contract. Simulated in Demo Mode only.',
  },
  {
    feature: 'Security Audit Logs',
    productionEndpoint: null,
    productionSupported: false,
    demoSupported: true,
    roleRequired: 'Admin',
    status: 'pending_backend',
    notes: 'Endpoint /audit-logs not in current API contract. Simulated in Demo Mode only.',
  },
  {
    feature: 'Usage Summary (KPIs)',
    productionEndpoint: 'GET /api/v1/organizations/{org_id}/usage/summary',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member+',
    status: 'confirmed',
    notes: 'Aggregated total calls, minutes, leads, conversion rate, avg duration, handoffs.',
  },
  {
    feature: 'Usage Analytics & Time Series',
    productionEndpoint: 'GET /api/v1/organizations/{org_id}/usage/analytics',
    productionSupported: true,
    demoSupported: true,
    roleRequired: 'Member+',
    status: 'confirmed',
    notes: 'Time-series call volume, hourly heatmaps, sentiment distributions.',
  },
];
